-- AlterEnum
ALTER TYPE "GraphEdgeKind" ADD VALUE 'CONFIGURES';
ALTER TYPE "GraphEdgeKind" ADD VALUE 'USES';
ALTER TYPE "GraphEdgeKind" ADD VALUE 'PROVIDES';
ALTER TYPE "GraphEdgeKind" ADD VALUE 'QUEUE_TOPIC';