/**
 * Canonical audit action identifiers. Every mutation across web and worker must use one of
 * these so the audit trail is queryable and consistent.
 */
export const AuditAction = {
  ORGANIZATION_CREATED: "organization.created",
  USER_LOGIN: "user.login",
  USER_LOGOUT: "user.logout",
  REPOSITORY_REGISTERED: "repository.registered",
  REPOSITORY_ARCHIVED: "repository.archived",
  SCAN_QUEUED: "scan.queued",
  SCAN_STARTED: "scan.started",
  SCAN_COMPLETED: "scan.completed",
  SCAN_FAILED: "scan.failed",
  CHANGE_DETECTED: "change.detected",
  CHANGE_TRIAGED: "change.triaged",
  CHANGE_NORMALIZED: "change.normalized",
  CHANGE_ANALYZED: "change.analyzed",
  CHANGE_IGNORED: "change.ignored",
  CHANGE_RESOLVED: "change.resolved",
  IMPACT_ASSESSED: "impact.assessed",
  PLAN_CREATED: "plan.created",
  PLAN_VALIDATION_QUEUED: "plan.validation_queued",
  PLAN_VALIDATION_STARTED: "plan.validation_started",
  PLAN_VALIDATION_PASSED: "plan.validation_passed",
  PLAN_VALIDATION_FAILED: "plan.validation_failed",
  POLICY_DECISION: "policy.decision",
  POLICY_BLOCKED: "policy.blocked",
  APPROVAL_RECORDED: "approval.recorded",
  PR_CREATED: "pull_request.created",
  PR_FAILED: "pull_request.failed",
  PR_STATUS_SYNCED: "pull_request.status_synced",
  GITHUB_INSTALLATION_SYNCED: "github.installation_synced",
  POLICY_CREATED: "policy.created",
  POLICY_UPDATED: "policy.updated",
  VENDOR_TOGGLED: "vendor.toggled",
  AGENT_EVENT_RECEIVED: "agent.event_received",
  AGENT_KEY_ISSUED: "agent.key_issued",
  SUBMISSION_RECEIVED: "submission.received",
  SUBMISSION_DEDUPLICATED: "submission.deduplicated",
  TASK_CLAIMED: "task.claimed",
  TASK_COMPLETED: "task.completed",
  TASK_FAILED: "task.failed",
  GRAPH_INDEX_QUEUED: "graph.index_queued",
  GRAPH_INDEX_STARTED: "graph.index.started",
  GRAPH_INDEX_COMPLETED: "graph.index.completed",
  GRAPH_INDEX_FAILED: "graph.index.failed",
  GRAPH_INDEX_REUSED: "graph.index.reused",
  RELEASE_RECORDED: "release.recorded",
  RELEASE_CLASSIFIED: "release.classified",
  RELEASE_CLASSIFICATION_FAILED: "release.classification_failed",
  RELEASE_MATCHED: "release.matched",
  RELEASE_MATCH_FAILED: "release.match_failed",
  AGENT_RUN_QUEUED: "agent.run_queued",
  AGENT_RUN_STARTED: "agent.run.started",
  AGENT_RUN_COMPLETED: "agent.run.completed",
  AGENT_RUN_FAILED: "agent.run.failed",
  AGENT_RUN_CANCELLED: "agent.run.cancelled",
  AGENT_RUN_BUDGET_EXCEEDED: "agent.run.budget_exceeded",
  AGENT_RUN_REPLAYED: "agent.run.replayed",
  DETECTION_RUN_STARTED: "detection.run.started",
  DETECTION_RUN_COMPLETED: "detection.run.completed",
  DETECTION_RUN_FAILED: "detection.run.failed",
  BILLING_CHECKOUT_STARTED: "billing.checkout_started",
  BILLING_PORTAL_STARTED: "billing.portal_started",
  SUBSCRIPTION_CHANGED: "subscription.changed",
  SUBSCRIPTION_CANCELED: "subscription.canceled",
  DEMO_RUN: "demo.run",
  DEMO_RESET: "demo.reset",
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
