# ---------------------------------------------------------------------------
# Patchbay - single multi-stage image, two processes.
#
# One image, two Railway services:
#   - web    -> `pnpm --filter @patchbay/web start`   (Next.js on PORT)
#   - worker -> `pnpm --filter @patchbay/worker start` (BullMQ consumer via tsx)
#
# The process is selected by APP_PROCESS (web|worker). RAILWAY_SERVICE_NAME
# is the fallback, so a Railway service literally named "worker" also works
# without extra configuration. The worker is NEVER started inside the Next.js
# server - it is a separate process owned by a separate Railway service.
# ---------------------------------------------------------------------------

# ---- base: Node 22 runtime + pinned pnpm -----------------------------------
FROM node:22-slim AS base
RUN npm install -g pnpm@10.34.5
WORKDIR /app

# NOTE: NODE_ENV is intentionally NOT set here. `pnpm install` skips
# devDependencies when NODE_ENV=production, and the Next.js build (and the
# worker's tsx runtime) need them. NODE_ENV=production is set in later stages.

# ---- deps: frozen full-workspace install ------------------------------------
# prisma client is generated by its postinstall hook (allowlisted in
# package.json `pnpm.onlyBuiltDependencies`), so no extra step is required.
FROM base AS deps
COPY . .
# Every pnpm start script loads `dotenv -e ../../.env`; Railway injects real
# values as environment variables, so an empty file is enough (dotenv never
# overrides variables that are already set).
RUN touch .env && pnpm install --frozen-lockfile

# ---- web-build: prisma generate + next build ---------------------------------
FROM deps AS web-build
ENV NODE_ENV=production
# Only consumed if a server module reads env at import time during `next
# build`; Railway injects the real DATABASE_URL at runtime. Never touched
# at runtime.
ARG DATABASE_URL=postgresql://patchbay_build:patchbay_build@localhost:5432/patchbay_build?schema=public
ENV DATABASE_URL=$DATABASE_URL
RUN pnpm db:generate && pnpm --filter @patchbay/web build

# ---- final: everything the web and worker processes need ---------------------
FROM node:22-slim AS final
RUN npm install -g pnpm@10.34.5
ENV NODE_ENV=production
WORKDIR /app
COPY --from=web-build /app /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 3000
CMD ["sh", "/entrypoint.sh"]
