/**
 * Patch safety scanner.
 *
 * Patches are generated by the deterministic remediation engine over content
 * that lives in the scanned repository — which may itself be hostile (a
 * fixture repo, a PR branch, an agent payload). Before a patch is persisted
 * or validated, its PATCHED content is scanned for constructs that must
 * never ship: dynamic code execution, shell metacharacters, path escapes,
 * credential literals. The scan is deliberately conservative and
 * pattern-based; it is a gate, not a proof.
 */

export interface PatchSafetyFinding {
  filePath: string;
  reason: string;
}

export type PatchSafetyVerdict = {
  safe: boolean;
  findings: PatchSafetyFinding[];
};

/** Pattern -> reason. Case-insensitive by default. */
const DANGEROUS_PATTERNS: Array<{ pattern: RegExp; reason: string }> = [
  {
    pattern: /(?:child_process|\bexecSync?\s*\(|\bspawn(?:Sync)?\s*\(|process\.exec)/i,
    reason: "dynamic process execution",
  },
  {
    pattern: /\beval\s*\(|new\s+Function\s*\(/i,
    reason: "dynamic code execution",
  },
  {
    pattern: /\bvm\.(?:runInThisContext|runInNewContext|compileFunction|Script)\b/i,
    reason: "sandboxed-execution escape surface",
  },
  {
    pattern:
      /\brm\s+-\s*rf?\b|\bchmod\s+777\b|\bsudo\b|\$\s*\([a-z]|\bcurl\s+[^\n|]{0,120}\s*\|\s*(?:sh|bash)\b/i,
    reason: "shell constructs",
  },
  {
    pattern:
      /;\s*(?:rm|curl|wget|sh|bash|sudo|nc|ncat|telnet|python|node|perl)\b|\|\s*(?:sh|bash|sudo|nc|ncat|telnet)\b/i,
    reason: "command chaining",
  },
  {
    pattern:
      /\.\.\/(?:\.\.\/)+|\bC:\\(?:Windows|Users|Program Files)|\/etc\/|\/usr\/|\/bin\/|\/tmp\//i,
    reason: "path outside the repository",
  },
  {
    pattern:
      /\b(?:sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{30,}|AKIA[A-Z0-9]{16}|AIza[A-Za-z0-9_-]{30,})\b/,
    reason: "credential literal",
  },
  {
    pattern: /(?:passwd|password|secret|token|api[_-]?key)\s*[:=]\s*['"][^'"]{6,}['"]/i,
    reason: "hardcoded secret assignment",
  },
];

export function scanPatchSafety(filePath: string, patchedContent: string): PatchSafetyFinding[] {
  const findings: PatchSafetyFinding[] = [];
  for (const { pattern, reason } of DANGEROUS_PATTERNS) {
    if (pattern.test(patchedContent)) {
      findings.push({ filePath, reason });
    }
  }
  return findings;
}

export function scanPatches(
  patches: Array<{ filePath: string; patched: string }>,
): PatchSafetyVerdict {
  const findings = patches.flatMap((patch) => scanPatchSafety(patch.filePath, patch.patched));
  return { safe: findings.length === 0, findings };
}
