import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { analyzeRepository } from "./analyzer";
import { extractPythonUsages, parsePyProjectToml, parseRequirementsTxt } from "./python";
import { UsageType } from "@patchbay/domain";

function fixtureDir(name: string): string {
  return path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../../../fixtures/repositories",
    name,
  );
}

describe("python manifest parsing", () => {
  it("parses PEP 621 project dependencies", () => {
    const manifest = parsePyProjectToml(`
[build-system]
requires = ["setuptools"]

[project]
name = "acme-app"
version = "1.2.3"
dependencies = [
  "openai>=1.0.0",
  "stripe[async]>=8.0.0 ; python_version >= '3.9'",
  "requests",
]

[project.optional-dependencies]
dev = ["pytest", "twilio>=9.0.0"]
`);
    expect(manifest.name).toBe("acme-app");
    expect(manifest.version).toBe("1.2.3");
    expect(Object.keys(manifest.dependencies).sort()).toEqual(["openai", "requests", "stripe"]);
    expect(Object.keys(manifest.devDependencies).sort()).toEqual(["pytest", "twilio"]);
  });

  it("parses poetry-style dependency tables", () => {
    const manifest = parsePyProjectToml(`
[tool.poetry]
name = "acme-app"
version = "0.9.0"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.30.0"
stripe = ">=8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
`);
    expect(manifest.name).toBe(null);
    expect(manifest.dependencies).toEqual({ openai: "^1.30.0", stripe: ">=8.0" });
    expect(manifest.devDependencies).toEqual({ pytest: "^8.0" });
  });

  it("parses requirements.txt with comments, extras, and markers", () => {
    const manifest = parseRequirementsTxt(`
# generated by uv
openai==1.35.0
stripe[async]>=8.2.0
twilio==9.0.0 ; python_version >= "3.9"
-r other.txt
--index-url https://example.invalid/simple
-e .
`);
    expect(Object.keys(manifest.dependencies).sort()).toEqual(["openai", "stripe", "twilio"]);
    expect(manifest.dependencies.openai).toBe("openai==1.35.0");
  });
});

describe("python L1 usage extraction (tree-sitter)", () => {
  const track = new Set(["openai", "stripe", "twilio"]);

  it("records imports, client construction, and method calls through imported modules", async () => {
    const source = [
      "import openai",
      "from stripe import StripeClient",
      "import twilio.rest as tw",
      "openai.chat.completions.create(messages=[])",
      "client = StripeClient('sk_test')",
      "tw.api.account.fetch()",
      "import json",
      "",
    ].join("\n");
    const usages = await extractPythonUsages(source, "src/app.py", track);
    expect(usages).toHaveLength(6);
    const imports = usages.filter((u) => u.usageType === UsageType.IMPORT);
    expect(imports.map((u) => u.packageName).sort()).toEqual(["openai", "stripe", "twilio"]);
    const inits = usages.filter((u) => u.usageType === UsageType.INITIALIZATION);
    expect(inits.map((u) => u.symbol)).toEqual(["StripeClient"]);
    expect(inits[0]?.packageName).toBe("stripe");
    const calls = usages.filter((u) => u.usageType === UsageType.METHOD_CALL);
    expect(calls.map((u) => u.symbol).sort()).toEqual([
      "openai.chat.completions.create",
      "tw.api.account.fetch",
    ]);
  });

  it("tracks the official-style v1 client pattern end to end", async () => {
    const source = [
      "from openai import OpenAI",
      "client = OpenAI(api_key='sk-test')",
      "completion = client.chat.completions.create(model='gpt-4o-mini', messages=[])",
      "return completion.choices[0].message.content",
      "",
    ].join("\n");
    const usages = await extractPythonUsages(source, "src/chat.py", track);
    expect(usages).toHaveLength(3);
    const init = usages.find((u) => u.usageType === UsageType.INITIALIZATION);
    expect(init?.packageName).toBe("openai");
    expect(init?.symbol).toBe("OpenAI");
    const call = usages.find((u) => u.usageType === UsageType.METHOD_CALL);
    expect(call?.packageName).toBe("openai");
    expect(call?.symbol).toBe("client.chat.completions.create");
    expect(call?.filePath).toBe("src/chat.py");
    expect(call?.line).toBeGreaterThan(0);
  });

  it("ignores untracked packages", async () => {
    const usages = await extractPythonUsages(
      "import requests\nimport django\nrequests.get('https://x')\n",
      "src/app.py",
      track,
    );
    expect(usages).toHaveLength(0);
  });

  it("handles aliased imports", async () => {
    const usages = await extractPythonUsages(
      "import openai as oai\nfrom stripe import StripeClient as SC\n",
      "src/app.py",
      track,
    );
    expect(usages).toHaveLength(2);
    const openai = usages.find((u) => u.packageName === "openai");
    expect(openai?.symbol).toBe("openai");
  });

  it("is deterministic across parses", async () => {
    const source = "import openai\nopenai.resources.chat.completions.create(messages=[])\n";
    const first = await extractPythonUsages(source, "src/app.py", track);
    const second = await extractPythonUsages(source, "src/app.py", track);
    expect(first).toEqual(second);
  });
});

describe("openai-python-legacy fixture", () => {
  it("indexes python manifests, usages, and call sites for certified packages", async () => {
    const analysis = await analyzeRepository({
      rootDir: fixtureDir("openai-python-legacy"),
      trackPackages: ["openai", "stripe", "twilio"],
    });

    expect(analysis.pythonFiles).toBeGreaterThan(0);
    expect(analysis.errors).toEqual([]);

    const manifest = analysis.pythonManifests[0];
    expect(manifest?.path).toBe("pyproject.toml");
    expect(Object.keys(manifest?.dependencies ?? {})).toEqual(
      expect.arrayContaining(["openai", "stripe", "twilio"]),
    );

    const openaiUsages = analysis.usages.filter((u) => u.packageName === "openai");
    expect(openaiUsages.length).toBeGreaterThan(0);
    expect(openaiUsages.some((u) => u.usageType === UsageType.IMPORT)).toBe(true);
    expect(
      openaiUsages.some((u) => u.usageType === UsageType.INITIALIZATION && u.symbol === "OpenAI"),
    ).toBe(true);
    expect(
      openaiUsages.some(
        (u) =>
          u.usageType === UsageType.METHOD_CALL && u.symbol.includes("chat.completions.create"),
      ),
    ).toBe(true);
    expect(openaiUsages.every((u) => u.filePath === "src/chat.py")).toBe(true);

    expect(
      analysis.usages.some(
        (u) => u.packageName === "stripe" && u.symbol === "client.customers.create",
      ),
    ).toBe(true);
    expect(
      analysis.usages.some(
        (u) => u.packageName === "twilio" && u.symbol === "client.messages.create",
      ),
    ).toBe(true);
  });

  it("does not index usages of untracked packages (requests)", async () => {
    const analysis = await analyzeRepository({
      rootDir: fixtureDir("openai-python-legacy"),
      trackPackages: ["openai", "stripe", "twilio"],
    });

    expect(analysis.usages.some((u) => u.packageName === "requests")).toBe(false);
    expect(analysis.usages.some((u) => u.excerpt.includes("requests.get"))).toBe(false);
  });
});

describe("analyzeRepository python integration", () => {
  it("indexes python files, manifests, and usages deterministically", async () => {
    const rootDir = await mkdtemp(path.join(tmpdir(), "patchbay-py-"));
    await writeFile(
      path.join(rootDir, "pyproject.toml"),
      [
        "[project]",
        'name = "py-app"',
        'version = "0.1.0"',
        'dependencies = ["openai>=1.0.0", "stripe>=8.0.0"]',
        "",
        "[project.optional-dependencies]",
        'dev = ["twilio"]',
        "",
      ].join("\n"),
    );
    await writeFile(
      path.join(rootDir, "app.py"),
      "import openai\nopenai.chat.completions.create(messages=[])\n",
    );
    await writeFile(
      path.join(rootDir, "stripe_client.py"),
      "from stripe import StripeClient\nclient = StripeClient('sk_test')\n",
    );

    const first = await analyzeRepository({
      rootDir,
      trackPackages: ["openai", "stripe", "twilio"],
    });
    expect(first.pythonFiles).toBe(2);
    expect(first.filesScanned).toBe(3);
    expect(first.pythonManifests).toHaveLength(1);
    expect(Object.keys(first.pythonManifests[0]?.dependencies ?? {}).sort()).toEqual([
      "openai",
      "stripe",
    ]);
    expect(first.pythonManifests[0]?.devDependencies).toEqual({ twilio: "twilio" });
    expect(first.usages).toHaveLength(4);
    expect(first.errors).toEqual([]);

    const second = await analyzeRepository({
      rootDir,
      trackPackages: ["openai", "stripe", "twilio"],
    });
    expect(second.commitSha).toBe(first.commitSha);
    expect(second.usages).toEqual(first.usages);
  });
});
